package net.omori_sunny.create_waterparked.content.attachment

import net.minecraft.core.BlockPos
import net.minecraft.nbt.CompoundTag
import net.minecraft.world.level.Level
import net.minecraft.world.phys.AABB
import net.minecraft.world.phys.Vec3

// everything a model needs to build itself: the resolved tube frame at the
// attachment's (t, angle) plus the slide's radius/thickness and the host
// block. Subclasses pick what they need.
data class SlideAttachmentModelContext(
    val level: Level,
    val sabPos: BlockPos,
    // attachment anchor on the outer wall: position + frame basis
    val position: Vec3,
    val tangent: Vec3,
    val lateral: Vec3,
    val up: Vec3,
    // radial-out direction at the attachment angle (into the tube = negated)
    val radialOut: Vec3,
    val radius: Float,
    val wallThickness: Float,
    val data: CompoundTag
) {
    /** local attachment-space AABB (origin at the wall point, +z = tangent) */
    fun localAABB(sx: Double, sy: Double, sz: Double, ex: Double, ey: Double, ez: Double): AABB =
        AABB(sx, sy, sz, ex, ey, ez)
}

// model source of an attachment type: returns the parts that together form
// the attachment visual. Procedural parts are code-defined boxes; json parts
// are block models - both live in local attachment space (x = lateral, y =
// up, z = tangent, origin at the wall point) and may combine freely.
abstract class SlideAttachmentModelProvider {

    /** outline box for the placement preview, in local attachment space */
    abstract fun boundingBox(ctx: SlideAttachmentModelContext): AABB

    open fun parts(ctx: SlideAttachmentModelContext): List<Part> = emptyList()

    sealed interface Part

    /** solid colored box centred at (cx, cy, cz), optionally rolled around z */
    data class BoxPart(
        val cx: Double,
        val cy: Double,
        val cz: Double,
        val sizeX: Double,
        val sizeY: Double,
        val sizeZ: Double,
        val rollDeg: Double = 0.0,
        val color: Int = 0xFF9C6B,
        val alpha: Int = 255
    ) : Part

    /** block model posed in local attachment space */
    data class ModelPart(
        val model: net.minecraft.client.resources.model.ModelResourceLocation,
        val offsetX: Double = 0.0,
        val offsetY: Double = 0.0,
        val offsetZ: Double = 0.0,
        val rollDeg: Double = 0.0,
        val pitchDeg: Double = 0.0,
        val scale: Double = 1.0
    ) : Part

    /** raw manually-built quad in local attachment space */
    data class Quad(
        val x0: Double, val y0: Double, val z0: Double,
        val x1: Double, val y1: Double, val z1: Double,
        val x2: Double, val y2: Double, val z2: Double,
        val x3: Double, val y3: Double, val z3: Double,
        val u0: Float, val v0: Float,
        val u1: Float, val v1: Float,
        val u2: Float, val v2: Float,
        val u3: Float, val v3: Float,
        val nx: Double, val ny: Double, val nz: Double
    )

    /** fully manual geometry - side walls generated by hand, no clipping */
    data class PolygonPart(val quads: List<Quad>) : Part
}
