package net.omori_sunny.create_waterparked.content.attachment

import com.simibubi.create.content.trains.track.BezierConnection
import net.minecraft.core.BlockPos
import net.minecraft.nbt.CompoundTag
import net.minecraft.world.level.Level
import net.minecraft.world.phys.AABB
import net.minecraft.world.phys.Vec3
import net.omori_sunny.create_waterparked.content.waterslide.WaterslideSectorConfig

data class SlideAttachmentModelContext(
    val level: Level,
    val sabPos: BlockPos,
    val position: Vec3,
    val tangent: Vec3,
    val lateral: Vec3,
    val up: Vec3,
    val radialOut: Vec3,
    val radius: Float,
    val wallThickness: Float,
    val data: CompoundTag,
    val t: Float,
    val curve: BezierConnection,
    val sectorConfig: WaterslideSectorConfig? = null,
    val renderTransform: SlideAttachmentRenderTransform? = null,
    val sectionRadii: FloatArray? = null,
    val baseRadius: Float = radius
) {
    fun localAABB(sx: Double, sy: Double, sz: Double, ex: Double, ey: Double, ez: Double): AABB =
        AABB(sx, sy, sz, ex, ey, ez)

    fun sectionMultAt(angleDeg: Float): Float =
        if (sectionRadii == null) 1f
        else net.omori_sunny.create_waterparked.game.SlideProfile.multiplierAt(sectionRadii, angleDeg)

    val sectionMaxMult: Float
        get() = sectionRadii?.max() ?: 1f
}

abstract class SlideAttachmentModelProvider {

    abstract fun boundingBox(ctx: SlideAttachmentModelContext): AABB

    open fun parts(ctx: SlideAttachmentModelContext): List<Part> = emptyList()

    sealed interface Part

    data class BoxPart(
        val cx: Double,
        val cy: Double,
        val cz: Double,
        val sizeX: Double,
        val sizeY: Double,
        val sizeZ: Double,
        val rollDeg: Double = 0.0,
        val color: Int = 0xFF9C6B,
        val alpha: Int = 255
    ) : Part

    data class ModelPart(
        val model: net.minecraft.client.resources.model.ModelResourceLocation,
        val offsetX: Double = 0.0,
        val offsetY: Double = 0.0,
        val offsetZ: Double = 0.0,
        val rollDeg: Double = 0.0,
        val pitchDeg: Double = 0.0,
        val scale: Double = 1.0
    ) : Part

    data class Quad(
        val x0: Double, val y0: Double, val z0: Double,
        val x1: Double, val y1: Double, val z1: Double,
        val x2: Double, val y2: Double, val z2: Double,
        val x3: Double, val y3: Double, val z3: Double,
        val u0: Float, val v0: Float,
        val u1: Float, val v1: Float,
        val u2: Float, val v2: Float,
        val u3: Float, val v3: Float,
        val nx: Double, val ny: Double, val nz: Double
    )

    /** fully manual geometry - side walls generated by hand, no clipping */
    data class PolygonPart(val quads: List<Quad>) : Part

    /** quads textured from a standalone repeating texture, uv counted in texture tiles */
    data class TiledPart(
        val quads: List<Quad>,
        val texture: net.minecraft.resources.ResourceLocation,
        val scroll: Float = 0f
    ) : Part
}
